#!/usr/bin/bash

xhost +local:root
docker run -it --network='host' --env='DISPLAY' --env='QT_X11_NO_MITSHM=1' --volume='/tmp/.X11-unix:/tmp/.X11-unix:rw' --volume='/home/leo/sublime:/sublime' 12345678910007/ros2:pub_sub bash
